# Generated by Django 4.2 on 2024-04-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_balance_options_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
