# Generated by Django 5.0.1 on 2024-01-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='people_you_may_know',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
    ]
