# Generated by Django 4.2 on 2024-04-24 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('one_spending', models.IntegerField()),
                ('spending_type', models.CharField(choices=[('medications', 'medications'), ('products', 'products'), ('entertainment', 'entertainment'), ('electronics', 'electronics'), ('trips', 'trips'), ('cloth', 'cloth'), ('present', 'present'), ('other', 'other')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
